pub mod criterion_1_0;
pub mod criterion_1_1;
pub mod criterion_1_2;
pub mod criterion_1_3;
pub mod criterion_4_0;
pub mod criterion_5_0;
pub mod criterion_6_structural;
pub mod struct_lzma;
pub mod struct_deflate;
pub mod struct_bwt;
mod criterion_3_0;
mod criterion_5_1;
